# Generated by Django 3.0.4 on 2020-03-20 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='job',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='questions',
            name='author',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='questions',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='questions',
            name='publishing_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='questions',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='questions',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='pseudo',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default=None)),
                ('publishing_date', models.DateTimeField(default=None)),
                ('author', models.CharField(default=None, max_length=255)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Users')),
            ],
        ),
    ]
