# Generated by Django 3.0.4 on 2020-03-27 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_questions_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='author',
        ),
        migrations.RemoveField(
            model_name='response',
            name='author',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='questions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Users'),
        ),
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Users'),
        ),
    ]
