# Generated by Django 3.0.4 on 2020-03-20 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_users_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='author',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='questions',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='questions',
            name='publishing_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='questions',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='questions',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='job',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='pseudo',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
