# Generated by Django 3.0.4 on 2020-03-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200320_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='publishing_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
