# Generated by Django 3.0.4 on 2020-03-29 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200327_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Questions'),
        ),
    ]
