# Generated by Django 3.0.4 on 2020-03-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200329_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
