# Generated by Django 3.0.4 on 2020-03-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200329_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='updated_date',
        ),
    ]
